# @file
# .travis.yml - Drupal for Travis CI Integration
#
# Template provided by https://github.com/LionsAd/drupal_ti.
#
# Based for simpletest upon:
#   https://github.com/sonnym/travis-ci-drupal-module-example

# Declare testing language
language: php

# Container infrastructure
sudo: false

# Language versioning
php:
  - 5.4

script:
  - echo ${SLACK_USER}
  - echo ${SLACK_TOKEN}

notifications:
  slack: ${SLACK_USER}:2bEjIi41VlFH25ikExKRrJ3i
